apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: gym-dev
data:
  PORT: "4000"
  DB_HOST: "<db-endpoint>"
  DB_PORT: "5432"
  DB_NAME: "gym_auth"
  SALT_ROUNDS: "10"
  JWT_EXPIRY: "1h"
