apiVersion: v1
kind: Secret
metadata:
  name: auth-postgres-credentials
  namespace: gym-dev
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "devpass"
  POSTGRES_DB: "auth_db"